name: Lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: latest
          args: --timeout 10m
